### ISSUE TITLE
add core helper libs

### ISSUE THREAD

**Issue by hone** [heroku/libcnb.rs#10]

**Comment by Malax** [comment]
IIRC, this is stuff that we have in `libherokubuildpack` right now. Download, untar helpers, etc. Basically everything that's easy to do in a bash buildpack but a little bit harder in Rust. Is this correct @hone?

If so, I think we should put this on hold for now until we figured out what exactly we want and letting the core libcnb API mature a bit.

**Comment by hone** [comment]
Yeah, though I've been thinking about the split b/t `libcnb-sys` (or `-data`) and `libcnb` that is more helpful. Stuff like download utils is generally useful vs. heroku specific. WDYT? We can just have 2 crates in here.
