### ISSUE TITLE
`StackId` should support the "any" stack (`"*"`)

### ISSUE THREAD

**Issue by edmorley** [heroku/libcnb.rs#104]
As of Buildpack API 0.5, a buildpack can declare support for any stack using a stack ID of `"*"`:
https://github.com/buildpacks/rfcs/blob/main/text/0056-any-stack-buildpacks.md
https://github.com/buildpacks/spec/blob/main/buildpack.md#buildpack-implementations
https://github.com/buildpacks/spec/blob/main/platform.md#stack-id

However this isn't currently supported:

```rust
use std::str::FromStr;
use libcnb::data::buildpack::BuildpackId;

let valid = BuildpackId::from_str("*");
assert_eq!(valid.unwrap().as_str(), "*");
```

Gives:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: InvalidBuildpackId("*")', src/data/buildpack.rs:8:18
```

Due to:
https://github.com/Malax/libcnb.rs/blob/f46bdda85838c9cc21cd1de3243d4160b85afc12/src/data/buildpack.rs#L209-L224

In addition, there is no validation that `mixins` is not set when the any stack is used (which is forbidden by the spec).

GUS-W-10055742

**Comment by schneems** [comment]
In this example:

```rs
use std::str::FromStr;
use libcnb::data::buildpack::BuildpackId;

let valid = BuildpackId::from_str("*");
assert_eq!(valid.unwrap().as_str(), "*");
```

I think you mean:

```rs
use std::str::FromStr;
use libcnb::data::buildpack::StackId;

let valid = StackId::from_str("*");
assert_eq!(valid.unwrap().as_str(), "*");
```

Regarding:

> In addition, there is no validation that mixins is not set when the any stack is used (which is forbidden by the spec).

I think that's the harder piece. `StackId` is used by `Stack` which is used by `BuildpackToml` and they're mostly there for serializing/deserializing. 

I found: 
- https://github.com/serde-rs/serde/issues/642
- https://github.com/serde-rs/serde/issues/939
- https://github.com/serde-rs/serde/issues/1118
-
