### ISSUE TITLE
a more fully featured maven buildpack example

### ISSUE THREAD

**Issue by hone** [heroku/libcnb.rs#11]

**Comment by Malax** [comment]
I don't think we need this anymore. We have a Ruby example that demonstrates the the usage of libcnb for a concrete language buildpack. The example would not demonstrate additional parts of the libcnb API beyond what the Ruby example does. Not sure where the value-add is here.

On the other hand, this is more code we need to maintain and not all maintainers have the context required to do so efficiently.

Thoughts @heroku/languages?
