### ISSUE TITLE
Make `libcnb-cargo` usable from workspace root

### ISSUE THREAD

**Issue by Malax** [heroku/libcnb.rs#215]
Currently, it can only be used from a buildpack project directory. Users might want to bundle multiple buildpacks in a Cargo workspace and build all buildpacks at once by running `cargo libcnb package` in the workspace root.

GUS-W-12731729.

**Comment by schneems** [comment]
To add in https://salesforce.quip.com/J3ZpAihiOAaZ. My ideal state would be to make building and releasing buildpacks converge to ~1 step. Being able to build all buildpacks in a workspace at the same time would help to get closer to that ideal.

**Comment by schneems** [comment]
Also maybe worth mentioning here: I took a spike at resolving buildpack dependencies based on their buildpack.toml entries awhile ago in ruby: https://github.com/schneems/omgcnb.

**Comment by edmorley** [comment]
I've filed W-10283507 to track this, under the cross-compiling epic.

**Comment by edmorley** [comment]
Once we update to Clap v3 we can then use:
https://crates.io/crates/clap-cargo

...which will make this much easier to implement.
