### ISSUE TITLE
API 0.7: Adjust buildpack version parts to be `u64`

### ISSUE THREAD

**Issue by edmorley** [heroku/libcnb.rs#269]
One of the changes in buildpack API 0.7 is:

>  Clarifies buildpack API must be u64 numbers ([#265](https://github.com/buildpacks/spec/pull/265)).

We'll want to change each of the major/minor/patch version parts to be `u64` here:
https://github.com/Malax/libcnb.rs/blob/7a8092a6d879c48ee0ee623002b77ad9b69bcf66/libcnb-data/src/buildpack/version.rs#L14-L18

**Comment by edmorley** [comment]
Ah this already happened in #241.

**Comment by Malax** [comment]
This wasn't fixed with #241 as that PR only dealt with a buildpack version. The change in CNB API 0.7 is for buildpack API versions, like `0.7`. This will be fixed in #489.
