### ISSUE TITLE
API 0.7: Support for SBOM

### ISSUE THREAD

**Issue by edmorley** [heroku/libcnb.rs#270]
In Buildpack API 0.7 there are several SBOM related changes.

> Build phase expects Software Bill of Materials (SBOM) to be output as files with the `application/vnd.cyclonedx+json`, `application/spdx+json`, or `application/vnd.syft+json` media type ([#269](https://github.com/buildpacks/spec/pull/269), [RFC 0095](https://github.com/buildpacks/rfcs/blob/main/text/0095-sbom.md)). The `[bom]` tables in launch.toml and build.toml are no longer supported.

There was also a followup change not mentioned in the release entry:
https://github.com/buildpacks/spec/pull/281

GUS-W-10426512.

**Comment by Malax** [comment]
I'd be interested implementing this if no one else feels the same way :)

**Comment by edmorley** [comment]
Go for it! :-)

**Comment by edmorley** [comment]
Also, when writing this issue up, I noticed the RFC seemed to refer to `.bom.` in the filenames, but yet the spec uses `.sbom.` -- it wasn't clear if this was a mistake in the RFC that needed reporting/changing upstream?

**Comment by hone** [comment]
@edmorley It's `.sbom` as written in the spec. It changed from the RFC but the old thing was called BOM which might have been why Sam wrote it that way in the RFC.

**Comment by edmorley** [comment]
@hone Thank for for the clarification. Ideally the RFC would be fixed retrospectively. The CNB project/specs have quite a lot of ambiguous/undefined behaviour, it really isn't ideal.
