### ISSUE TITLE
API for working with files inside a container

### ISSUE THREAD

**Issue by Malax** [heroku/libcnb.rs#279]
For some tests, verifying the contents of files written by the buildpack (or other tooling during the build process) is required. `ContainerContext` should be extended to allow downloading files from the container. For example:

```rust
fn get_file(path: AsRef<str>) -> Result<TempFile, _>
```

**Comment by edmorley** [comment]
Another way to inspect files would also be via #309 (which we'll need regardless). It might be we want to wait to hear about use-cases for this issue, before spending too much time implementing (in case they are pretty rare and/or mostly satisfied by #309).

**Comment by edmorley** [comment]
@Malax Do we still need this given we now have `libcnb-test` APIs for running arbitrary commands against containers? (eg `cat` then inspect log output etc).
