### ISSUE TITLE
Default `on_error` exit code for internal errors is incorrect

### ISSUE THREAD

**Issue by edmorley** [heroku/libcnb.rs#286]
The default `Buildpack::on_error` implementation (as well as the custom implementation we have in libherokubuildpack) uses an exit code of 100 if an internal buildpack error occurred:
https://github.com/Malax/libcnb.rs/blob/abe9b153535c543ec5f1a691a1f8c58b3c1413dd/libcnb/src/buildpack.rs#L46-L51

During the build phase this is fine, since all non-zero exit codes have the same meaning in the CNB spec:
https://github.com/buildpacks/spec/blob/main/buildpack.md#build

However during detect, an exit code of 100 means "fail detect" rather than "error":
https://github.com/buildpacks/spec/blob/main/buildpack.md#detection

Therefore for any buildpack where such an error occurs during detect (eg an IO error reading `buildpack.toml`), Pack will end up displaying a generic "no buildpacks passed detect" error, rather than surfacing the error message in the output.

**Comment by Malax** [comment]
Agreed, this is currently incorrect and we should fix it. I'll cook up something.
