### ISSUE TITLE
libcnb-test: Support running pack using `--verbose`

### ISSUE THREAD

**Issue by edmorley** [heroku/libcnb.rs#383]
The Pack CLI has a `--verbose` option. 

In some cases, the information provided by `--verbose` is essential to understanding what went wrong. 

For example, if detect fails, Pack by default only outputs:

```
===> DETECTING
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```

Whereas with `--verbose` you get:

```
===> DETECTING
======== Output: heroku/python@0.1.0 ========
<whatever output the buildpack printed to stdout/stderr>

======== Results ========
pass: heroku/python@0.1.0
Resolving plan... (try #1)
fail: heroku/python@0.1.0 provides unused python
ERROR: No buildpack groups passed detection.
ERROR: Please check that you are running against the correct path.
ERROR: failed to detect: no buildpacks participating
ERROR: failed to build: executing lifecycle: failed with status code: 20
```

Arguably the detect failure case is perhaps something pack should handle better itself (ie: print the output or reasons if detect fails, even if `--verbose` was not specified). 

However until such time as Pack fixes that, the only way to write integration tests against those error messages using `libcnb-test`, is if it provides a way to pass `--verbose` to Pack.

If this was the default it might make output quite noisy, but then having it opt it means yet another option / more friction when needing the verbose option for general debugging (rather than writing the tests mentioned above) - so I could go either way.

**Comment by Malax** [comment]
We even have support for adding `-v` to the `pack` command internally:
https://github.com/Malax/libcnb.rs/blob/06b33cca7fd845fcc2a07284321a9613749cca73/libcnb-test/src/pack.rs#L120-L122

WDYT about having an env var like `LIBCNB_TEST_PACK_VERBOSE` or similar that can be used to trigger the verbose behaviour? `LIBCNB_TEST_PACK_OPTS` is also a possibility, but I worry that we will overuse that instead of adding features properly into `libcnb-test`.

**Comment by edmorley** [comment]
I feel like there are also two improvements we need upstream:
1. Improved Pack UX when detect fails
2. Better guidance in the spec as to what buildpack authors should be outputting to stdout and/or stderr in a variety of "error" / "maybe error" / "probably not an error, but this information would help with debugging" type detect failure cases.

**Comment by edmorley** [comment]
So #415 will have helped with one of the original motivations for this feature request, in that detection errors will now be shown correctly without the need to use `--verbose`.

With that, I wonder if we still need this? Even without this change, people can still `pack build --verbose` themselves outside of `libcnb-test` tests etc.

**Comment by edmorley** [comment]
Closing for now given the above. We can always reopen if we find a need for this :-)

**Comment by edmorley** [comment]
So I needed this for a test I was hoping to write just now, which validated that when detect didn't pass (ie: it successfully completed, but exited 100 to indicate it shouldn't be included in the build), that the informative message printed to stdout was shown when using `--verbose`. 

In terms of implementation, it feels like adding a new `verbose` field + appropriate builder methods, to `BuildConfig` would be the best fit?

**Comment by Malax** [comment]
> In terms of implementation, it feels like adding a new verbose field + appropriate builder methods, to BuildConfig would be the best fit?

Sounds good to me! 👍🏻

**Comment by edmorley** [comment]
> So I needed this for a test I was hoping to write just now, which validated that when detect didn't pass (ie: it successfully completed, but exited 100 to indicate it shouldn't be included in the build), that the informative message printed to stdout was shown

This is no longer necessary, since lifecycle will output the detect stdout/stderr if no buildpacks pass detection, since:
https://github.com/buildpacks/lifecycle/pull/975
