### ISSUE TITLE
libcnb-test: Support compiling buildpacks with `--release`

### ISSUE THREAD

**Issue by edmorley** [heroku/libcnb.rs#386]
In GUS-W-10910805 / rust-lang/flate2-rs/issues/297, I found that when using `flate2` to decompress a downloaded file (the Python runtime archive), debug builds are so slow as to make them unusable for development iteration/testing, particularly when combined with Docker's QEMU performance issues on M1. (See the table of runtimes in that issue for more details.)

For manual testing using `cargo libcnb package` followed by `pack build`, I can work around this by passing `--release` to `cargo libcnb package`, however currently `libcnb-test` does not provide a way to request that the buildpack is compiled in release mode.

In addition to adding support for this being opt in, we should evaluate whether running in release mode should be the default (depends on where the break-even point is for compile time vs runtime, though effective `target/` caching can help with the former).

GUS-W-10912497.

**Comment by Malax** [comment]
The linked issue also [has a comment with an IMO sensible workaround](https://github.com/rust-lang/flate2-rs/issues/297#issuecomment-1081060316): bumping the optimisation level for debug up a notch in `Cargo.toml`:

```
[profile.dev]
opt-level = 1
```

**Comment by edmorley** [comment]
Yes I'm aware. I still think we should support this however.
