### ISSUE TITLE
Example Ruby buildpack actually uses system Ruby

### ISSUE THREAD

**Issue by edmorley** [heroku/libcnb.rs#398]
When I updated all usages of `heroku/buildpacks:20` in this repository to instead use `heroku/builder:22` the integration test for the example Ruby buildpack started failing.

After investigation, it turns out that the example Ruby buildpack is actually pretty broken at the moment.

For example, when the test runs, the image actually uses system Ruby, and so when run under `heroku/builder:22` (which is based on Heroku-22, which no longer has system Ruby), the image fails at runtime.

The reason it's falling back to system Ruby seems to be due to the manual `PATH` definition here, since it's missing the delimiter:
https://github.com/heroku/libcnb.rs/blob/6452900d4d5d3e198c8acc6fddb9d2b1e8f4cf4f/examples/ruby-sample/src/layers/ruby.rs#L46-L57

This then causes a broken `PATH`:

```
$ dr --entrypoint launcher test-ruby -- bash
heroku@b4cc8af292e1:/workspace$ env
...
PATH=/workspace/.gem/ruby/2.6.6/bin/layers/libcnb-examples_ruby/ruby/bin:/layers/libcnb-examples_ruby/bundler/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
LD_LIBRARY_PATH=/layers/libcnb-examples_ruby/ruby/layers/libcnb-examples_ruby/ruby/lib
```

(See also https://github.com/buildpacks/spec/issues/285)

I removed this manual `PATH` definition (which was also referencing Ruby 2.6, so completely wrong?), along with the seemingly also redundant `LD_LIBRARY_CONFIG` env var.

However then ran into another issue:

```
$ dr test-ruby
Could not find minitest-5.14.4 in any of the sources
Run `bundle install` to install missing gems.
```

As such, I'm going to exclude this example buildpack from the PR for `heroku/builder:22` -- we'll have to fix this example buildpack first.

cc @schneems @Malax

**Comment by joshwlewis** [comment]
@edmorley looks like this was closed accidentally, due to the reference link in #399.

**Comment by edmorley** [comment]
Good spot, thank you :-)

**Comment by edmorley** [comment]
In addition to the issue mentioned in the OP here, there are multiple other problems with the Ruby CNB example in this repo:
- #479
- #746
- #755

IMO we should just delete this example, and instead:
1. Longer term add better (and simpler) examples to this repo, demonstrating concepts such as layer use, downloading a binary etc. (But nothing as complex as an example purporting to support a full language, like the current Ruby example)
2. Link to our actual CNBs for the "fully fledged CNB" example use-case

**Comment by edmorley** [comment]
Wontfix since the Ruby example has been removed in #757.
