### ISSUE TITLE
Fix issues with `ruby-sample` integration test

### ISSUE THREAD

**Issue by edmorley** [heroku/libcnb.rs#479]
The test has several issues:
1. The test uses `call_test_fixture_service` rather than something more realistic like `ureq`
2. The web server isn't compliant with the HTTP spec (so attempts to use `ureq` to make a request to it fail)
3. The app is unnecessarily complicated - it does not need to accept a posted value and invert it - replying with a fixed string to a GET would do (eg just using a Ruby stdlib HTTP server)
4. It uses a hardcoded sleep, rather than something like: https://github.com/heroku/libcnb.rs/blob/2a75bb6fc6f3817b07891bd66a944bb9b3508323/libcnb-test/tests/integration_test.rs#L77-L87
5. It uses Ruby 2.7, so has to use the `heroku/buildpacks:20` builder image (rather than the `heroku/builder:22` used by other tests), which slows down CI as it means another builder image has to be pulled.

**Comment by schneems** [comment]
> The web server isn't compliant with the HTTP spec (so attempts to use ureq to make a request to it fail)

Can you give me some more context here? What fails?

**Comment by edmorley** [comment]
@schneems The test app is not a proper HTTP server, since it uses `TCPServer` and does not implement the correct HTTP protocol itself. It echos back the received payload reversed only, and is missing the status line, headers etc:
https://github.com/heroku/libcnb.rs/blob/main/examples/ruby-sample/test-fixtures/simple-ruby-app/app.rb

**Comment by edmorley** [comment]
Wontfix since the Ruby example has been removed in #757.
