### ISSUE TITLE
Add support for slice layers

### ISSUE THREAD

**Issue by schneems** [heroku/libcnb.rs#485]
To implement caching for a few heroku buildpack features with libcnb.rs (listed in https://github.com/heroku/buildpacks-ruby/tree/schneems/fresh-start-rust#application-contract-compile) I would like an implementation of slice layers https://github.com/buildpacks/spec/blob/main/buildpack.md#slice-layers.

A slice layer allows a buildpack to specify a layer that is within the application directory. So this will allow me to cache `<app-dir>/public/assets` without having to move files on disk around.

@Malax previously said this is a thing he thinks is easy to implement. Maybe if we're running short on time, if he can share thoughts on desired interface someone can try to stub out an implementation.

GUS-W-11486542.

**Comment by edmorley** [comment]
The relevant parts of the spec are here:
https://github.com/buildpacks/spec/blob/main/buildpack.md#slice-layers
https://github.com/buildpacks/spec/blob/main/buildpack.md#launchtoml-toml

I think all that needs changing is `libcnb-data`'s `Launch`:
https://github.com/heroku/libcnb.rs/blob/d65045275b7385a3bc01e98d00d71e04f3fe4cc1/libcnb-data/src/launch.rs#L5-L16
(I don't think any changes will be needed in `libcnb`)

**Comment by schneems** [comment]
The spec is really light on details for slice layers. I'm unsure if a `toml` file is needed to specify `cache=true` inside of the slice directory. It doesn't look like it. Which would make sense given that the purpose of a slice is to act as a cache that doesn't require disk moving. In that case I think you're right, I just have to point a dir and say it's a slice.

It would be good to support specifying slices in `BuildResultBuilder` which would (I think) mean an interface on `impl Launch` such as `fn slice` `fn slices`.

**Comment by Malax** [comment]
This has now been fixed via https://github.com/heroku/libcnb.rs/pull/487. However, I do think slice layers don't do what you want them to do. They won't be cached between app builds, the data in slice layers will only be exported as a dedicated OCI image layer so that different images can share the same layer if the contents are the same.

So in your use-case, you will have to copy files you want to cache between builds to a dedicated layers in the layers directory.

**Comment by schneems** [comment]
> They won't be cached 

:(
