### ISSUE TITLE
Want to buy: UncheckedLayerName

### ISSUE THREAD

**Issue by schneems** [heroku/libcnb.rs#523]
Currently you can only define a layer name if it's known at compile time via the `layer_name!` macro. If you try to define one manually:

```
                LayerName("hahah"),
```

You get:

```
error[E0423]: cannot initialize a tuple struct which contains private fields
  --> src/lib/in_app_dir_cache.rs:39:17
   |
39 |                 LayerName("hahah"),
   |                 ^^^^^^^^^
   |
note: constructor is not visible here due to private fields
```

I have a predictable pattern for programmatically constructing layer names and I don't want my end user to have to pass one in. I would like an `UnCheckedLayerName` (or something else) that allows me to generate a layer name that's not checked at compile time.

**Comment by edmorley** [comment]
This is already possible - see the docs for `LayerName`:
https://docs.rs/libcnb/latest/libcnb/data/layer/struct.LayerName.html

**Comment by Malax** [comment]
```rust
let user_input = "icanhazlayer";
let user_layer_name: LayerName = user_input.parse().unwrap();
```
