### ISSUE TITLE
Multi-Arch Directory Structure

### ISSUE THREAD

**Issue by hone** [heroku/libcnb.rs#579]
Currently when using `cargo libcnb package`, it outputs the resulting buildpack into `target/buildpack`. This works great in the default (single arch) use case, but if you want to support multiple archs they will clobber each other. What if we put `buildpack` inside an arch directory? For instance:

`target/buildpack/<mode>/<name>` -> `target/buildpack/<arch>/<mode>/<name>`

Another alternative but could just be a good addition would be an `--out-dir` like `cargo build` (though this is unstable atm).

**Comment by jasonschroeder-sfdc** [comment]
There may be patterns to follow from here... https://github.com/rust-lang/cargo/issues/8875
It reminds me of macOS universal binaries, where one file supports multi-arch.

I think `--out-dir` is more flexible (and could be used to implement the first option)

**Comment by Malax** [comment]
```target/buildpack/<mode>/<name> -> target/buildpack/<arch>/<mode>/<name>```

Is exactly what Cargo does in the regular target directory. I think keeping parity with Cargo itself is worthwhile, especially when we're using the same output directory. We did this for the command line arguments as well to keep the surprise factor low.
