### ISSUE TITLE
libcnb-test ergonomics: Missing error messages when container failed to boot but the assertion is on stdout (and not stderr)

### ISSUE THREAD

**Issue by schneems** [heroku/libcnb.rs#630]
This might already be fixed on main as Ed was mentioning improving some of these error cases.

## Issue

I had a bug in my execd script and this is the output I got:

```
thread 'test_barnes_app' panicked at 'assertion failed: `(left contains right)`
left (unescaped):
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/heroku_statsd-metrics/statsd-metrics-agent/exec.d/spawn agentmon': exit status 101


left (escaped): `"\u{1b}[31;1mERROR: \u{1b}[0mfailed to launch: exec.d: failed to execute exec.d file at path '/layers/heroku_statsd-metrics/statsd-metrics-agent/exec.d/spawn agentmon': exit status 101\n"`
right: `"agentmon_loop --path"`', buildpacks/metrics-agent/tests/integration_test.rs:28:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: integration_test::test_barnes_app::{{closure}}::{{closure}}
             at ./tests/integration_test.rs:28:21
   3: libcnb_test::test_context::TestContext::start_container
             at /Users/rschneeman/.cargo/git/checkouts/libcnb.rs-06ac117a90af1646/2042df4/libcnb-test/src/test_context.rs:116:9
   4: integration_test::test_barnes_app::{{closure}}
             at ./tests/integration_test.rs:18:13
   5: libcnb_test::test_runner::TestRunner::build_internal
             at /Users/rschneeman/.cargo/git/checkouts/libcnb.rs-06ac117a90af1646/2042df4/libcnb-test/src/test_runner.rs:177:9
   6: libcnb_test::test_runner::TestRunner::build
             at /Users/rschneeman/.cargo/git/checkouts/libcnb.rs-06ac117a90af1646/2042df4/libcnb-test/src/test_runner.rs:93:9
   7: integration_test::test_barnes_app
             at ./tests/integration_test.rs:9:5
   8: integration_test::test_barnes_app::{{closure}}
             at ./tests/integration_test.rs:8:22
   9: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

From this test code:

```rust
            context.start_container(
                ContainerConfig::new()
                    .entrypoint(["launcher"])
                    .envs(vec![
                        ("HEROKU_METRICS_URL", "example.com"),
                        ("DYNO", "web.1"),
                        ("PORT", "1234"),
                    ])
                    .command(["ps x"]),
                |container| {
                    let log_output = container.logs_wait();
                    assert_contains!(log_output.stdout, "agentmon_loop --path");
                },
            );
```

If I build and manually try to run: I get an error with a lot more information:

```
$ docker run -it --rm --entrypoint='/cnb/lifecycle/launcher' my-image-name 'ps x'
thread 'main' panicked at 'Command heroku-statsd-metrics: Short option names must be unique for each argument, but '-l' is in use by both 'log' and 'loop_path'', /Users/rschneeman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.17/src/builder/debug_asserts.rs:112:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/heroku_statsd-metrics/statsd-metrics-agent/exec.d/spawn-agentmon': exit status 101
```

The issue here is that the container is failing to boot, but the error message is on stderr not on stdout. We can hack around it by doing this:

```rust
                |container| {
                    let log_output = container.logs_wait();
                    println!("{}", log_output.stdout);
                    println!("{}", log_output.stderr);

                    assert_contains!(log_output.stdout, "agentmon_loop --path");
                },
```

Which gives us a better output:

```
test test_barnes_app ... FAILED

failures:

---- test_barnes_app stdout ----
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/heroku_statsd-metrics/statsd-metrics-agent/exec.d/spawn-agentmon': exit status 101

thread 'main' panicked at 'Command heroku-statsd-metrics: Short option names must be unique for each argument, but '-l' is in use by both 'log' and 'loop_path'', /Users/rschneeman/.cargo/registry/src/index.crates.io-6f17d22bba15001f/clap_builder-4.3.17/src/builder/debug_asserts.rs:112:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

thread 'test_barnes_app' panicked at 'assertion failed: `(left contains right)`
left (unescaped):
ERROR: failed to launch: exec.d: failed to execute exec.d file at path '/layers/heroku_statsd-metrics/statsd-metrics-agent/exec.d/spawn-agentmon': exit status 101


left (escaped): `"\u{1b}[31;1mERROR: \u{1b}[0mfailed to launch: exec.d: failed to execute exec.d file at path '/layers/heroku_statsd-metrics/statsd-metrics-agent/exec.d/spawn-agentmon': exit status 101\n"`
right: `"agentmon_loop --path"`', buildpacks/metrics-agent/tests/integration_test.rs:32:21
stack backtrace:
   0: rust_begin_unwind
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/std/src/panicking.rs:593:5
   1: core::panicking::panic_fmt
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/panicking.rs:67:14
   2: integration_test::test_barnes_app::{{closure}}::{{closure}}
             at ./tests/integration_test.rs:32:21
   3: libcnb_test::test_context::TestContext::start_container
             at /Users/rschneeman/.cargo/git/checkouts/libcnb.rs-06ac117a90af1646/2042df4/libcnb-test/src/test_context.rs:116:9
   4: integration_test::test_barnes_app::{{closure}}
             at ./tests/integration_test.rs:18:13
   5: libcnb_test::test_runner::TestRunner::build_internal
             at /Users/rschneeman/.cargo/git/checkouts/libcnb.rs-06ac117a90af1646/2042df4/libcnb-test/src/test_runner.rs:177:9
   6: libcnb_test::test_runner::TestRunner::build
             at /Users/rschneeman/.cargo/git/checkouts/libcnb.rs-06ac117a90af1646/2042df4/libcnb-test/src/test_runner.rs:93:9
   7: integration_test::test_barnes_app
             at ./tests/integration_test.rs:9:5
   8: integration_test::test_barnes_app::{{closure}}
             at ./tests/integration_test.rs:8:22
   9: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
  10: core::ops::function::FnOnce::call_once
             at /rustc/eb26296b556cef10fb713a38f3d16b9886080f26/library/core/src/ops/function.rs:250:5
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

But it's unintuitive to do this, and I've been discouraged from adding these types of seemingly random print lines previously.

**Comment by schneems** [comment]
I think this would be fixed/improved in https://github.com/heroku/libcnb.rs/commit/346a186b35a5941a593228b25d68a196c7e75116 if using that interface

**Comment by edmorley** [comment]
> I think this would be fixed/improved in [346a186](https://github.com/heroku/libcnb.rs/commit/346a186b35a5941a593228b25d68a196c7e75116) if using that interface

That interface is internal only, and for running commands not performing test assertions, so not really applicable here.

> We can hack around it by doing

So for this example (and if keeping the test using `start_container()`; more on this later), it would be better to write the test like:

```rust
                    let log_output = container.logs_wait();
                    assert_empty!(log_output.stderr);
                    assert_contains!(log_output.stdout, "agentmon_loop --path");
```

...which would mean you see the error message as expected, without the need for stray prints, and with a more explicit assertion.

ie:
- If the output is expected to be about something successful, first check stderr is empty, then check stdout for the successful message
- Or, if the output is expected to be about a failure, first check stdout is empty (or contains whatever part of the messaging that ends up on stdout), then check stderr for the error message

That way, in the case of the test not behaving as expected, the first assertion to fire always gives the needed information. This principal isn't really libcnb-specific, but is just how one needs to write tests when using a test framework that aborts after the first assert (which is the case for many frameworks in different languages).

Other than that, we would either need to:
1. Have a custom assertion macro that asserts against both stdout and stderr simultaneously, and outputs the contents of both if either assertion failed. (Though I think this might give less flexibility than having two assertions as seen above).
2. Adjust `assert_contains!` so it takes a third argument of a `LogOutput`, which could then be pretty-printed as part of the error message.
3. Implement #536 and then perform most of our assertions against the combined stdout/stderr instead, with only specific cases where we need to check stderr explicitly using the raw outputs

I think my preference would be for (3).

That all said, in the specific example given in the OP, it seems the `ps x` command should be being run using `TestContext::run_shell_command`, which requires less boilerplate and would have paniced for you with the stderr + stdout printed.

**Comment by schneems** [comment]
>                     assert_empty!(log_output.stderr);

I think this is a testing code smell. There are tons of cases when the stderr might not be empty, or it might be whitespace or perhaps someone has some code that checks the day of the year and emits 'Happy birthday to me" on a specific date. I think this specific check would be brittle. In practice there are plenty of times when it would be fine, but I don't like it for the general case.


Ideally, tests should seek to verify behaviors. That does have me thinking that since I don't care WHERE that content is output, just that the user sees it. I could do something like:

```rust
assert_contains!(format!("{}\n{}",  log_output.stderr, log_output.stdout), "agentmon_loop --path")
```

Also, it would require needing to know/remember this specific failure mode and add this guard proactively. By the time I figured out I would have needed something like this, I no longer needed something like this (because I understood the problem, at least on the first encounter).

> 1. Have a custom assertion macro that asserts against both stdout and stderr simultaneously, and outputs the contents of both if either assertion failed. (Though I think this might give less flexibility than having two assertions as seen above).

Interesting idea. Basically the same idea above. I think this is closer to the actual behavior I want to assert rather than verifying empty stderr. It still has the issue of the user needing to know about it. I think if it was the default in the docs or we put some "consider using feature X" in the docs for `assert_contains!` etc. It would still allow people the option of using the low level stdout/stderr with assert_contains.

> 2. Adjust assert_contains! so it takes a third argument of a LogOutput, which could then be pretty-printed as part of the error message.
>
> 3. Implement https://github.com/heroku/libcnb.rs/issues/536 and then perform most of our assertions against the combined stdout/stderr instead, with only specific cases where we need to check stderr explicitly using the raw outputs
>
> I think my preference would be for (3).

I voiced concern over the difficulty of capturing all three streams (stdout + stderr + stdout/stderr-combined) exactly as a user would see them in a slack thread. For the test experience, it's probably okay if it's not byte-for-byte perfect though, so I'm more open to it as a feature there.

Another 4th option is to do what Hatchet did/does and annotate build failures. In this case all of our logic is called from within a wrapping closure. We could catch panics, check if the contents already have the contents of stdout/stderr in them, and if not emit the build logs (or simply do it all the time even if it's duplicate output).

I would be happy with either 1 or 3 along with some doc updates.

> That all said, in the specific example given in the OP, it seems the ps x command should be being run using TestContext::run_shell_command, which requires less boilerplate and would (with the fixes on main) have panicked for you with the stderr + stdout printed.

I think this is the right answer. That was the functionality I was looking to link to in my original issue. I think we can close

**Comment by edmorley** [comment]
> Ideally, tests should seek to verify behaviors.

I absolutely agree, though:
(a) there will be cases where this isn't possible,
(b) part of the behaviours we need to be testing is the UX around log output - and part of that UX is "are there unexpected warnings/errors in the output" + "did we output things on stdout vs stderr as appropriate, or did we mix them up by accident".

> I think this is a testing code smell. There are tons of cases when the stderr might not be empty, or it might be whitespace or perhaps someone has some code that checks the day of the year and emits 'Happy birthday to me" on a specific date. I think this specific check would be brittle.

I agree that there may be some cases where it's awkward to assert against stderr, but I don't agree that it's a code smell to do so in the general case.

Bear in mind that libcnb-test is aimed at buildpack authors writing tightly controlled tests for their buildpacks, not for testing apps in general. Our tests and buildpacks should:
- not have fragile date based conditionals that then cause test output to shift
- be very explicit in their testing of output, and part of that includes what they output onto stderr

In addition, in the "stderr isn't empty but is some whitespace" case, you could `trim()` or whatever.

> Also, it would require needing to know/remember this specific failure mode and add this guard proactively. By the time I figured out I would have needed something like this

Testing the contents of stderr is a general best practice when dealing with components that output things onto stdout and stderr. The example assertion I gave isn't for the sole purpose of protecting against the confusion seen in the OP, it's for making sure that the buildpack doesn't somehow result in unforeseen warnings/errors at boot - and as an added bonus would then have also caught this case.

For example in the Python functions runtime tests (that have nothing to do with Rust, libcnb.rs or buildpacks), see that for the expected-successful tests I assert against stderr first before checking stdout:
https://github.com/heroku/sf-functions-python/blob/97a5dffb90f93824c3ab4c7dee214f9c5c825647/tests/test_cli.py#L93-L94

That's not to say that there aren't ways we can make it easier to test functionality/behaviours more easily directly (for example I think we want a helper for retrying making a request to webapps giving them time to boot etc), but even with those helpers I still think "being strict about asserting against stdout/stderr" is still a best practice we should be doing regardless.
