### ISSUE TITLE
libcnb-cargo Simplify the error mappings

### ISSUE THREAD

**Issue by colincasey** [heroku/libcnb.rs#634]
In `libcnb-cargo` all the packaging-related errors are defined on the `package::error::Error` enum which uses `thiserror` annotations to provide user-facing messages.  There are also several `impl From<T> for Error` mappings for internal errors that come from `libcnb-package` to flatten those specific errors into application errors.  This accomplishes the goal of having a specific user message for each possible error but comes with the side-effect that the `package::error::Error` enum is quickly becoming a large, unwieldy list.

A suggestion from @Malax was to provide a new trait that could be implemented for the `libcnb-package` errors that need to be mapped to application errors in `libcnb-cargo`.  E.g.;

```rust
#[derive(Debug, thiserror::Error)]
pub(crate) enum Error {
  //...
  #[error("Error finding workspace:\n{}", .0.to_error_message())]
  FindCargoWorkspace(FindCargoWorkspaceError),
}

trait ApplicationError {
    fn to_error_message(&self) -> String;
}

impl ApplicationError for FindCargoWorkspaceError {
    fn to_error_message(&self) -> String {
        match self {
            FindCargoWorkspaceError::GetCargoEnv(_) => {
                "No environment variable named `CARGO` is set".to_string()
            }
            FindCargoWorkspaceError::SpawnCommand(error) => {
                format!("Failed to spawn Cargo command\nError: {error}")
            }
            FindCargoWorkspaceError::CommandFailure(exit_status) => {
                format!(
                    "Unexpected Cargo exit status while attempting to read workspace root\nExit Status: {}\nExamine Cargo output for details and potential compilation errors.", 
                    exit_code_or_unknown(exit_status)
                )
            }
            FindCargoWorkspaceError::GetParentDirectory(path) => {
                format!(
                    "Could not locate a Cargo workspace within `{}` or it's parent directories",
                    path.display()
                )
            }
        }
    }
}
```

The benefit of this approach is:
* `package::error::Error` would not grow by `N` variants for each `libcnb-package` error
* `libcnb-cargo` still has control over the error message provided each `libcnb-package` error

**Comment by Malax** [comment]
Of note here: the reason for a new trait are Rust's orphan rules which prevent us from implementing `Display` for errors that come from a different crate. Specifically errors from usage of `libcnb-package` in `libcnb-cargo`.
