### ISSUE TITLE
Buildpack descriptor naming differs from spec

### ISSUE THREAD

**Issue by colincasey** [heroku/libcnb.rs#639]
The buildpack structs in `libcnb-data` are named `SingleBuildpackDescriptor` and `MetaBuildpackDescriptor` but the [terminology used is the spec](https://github.com/buildpacks/spec/blob/main/buildpack.md#cnb-terminology) is "component buildpack" and "composite buildpack". These structs should be renamed to `ComponentBuildpackDescriptor` and `CompositeBuildpackDescriptor`.

GUS-W-14161652.

**Comment by edmorley** [comment]
Yeah agree we should standardise on those names.

The reason we don't use them at present, is that they were only recently added to the terminology section (prior to that, there was no official word for them):
https://github.com/buildpacks/spec/issues/145

**Comment by Malax** [comment]
Cool to see official names for concepts coming from upstream. Having to come up with our own names was (and still is) one of the major annoyances for me.
