### ISSUE TITLE
Incorrect error message shown when cross-compile dependencies not installed

### ISSUE THREAD

**Issue by jose-fully-ported** [heroku/libcnb.rs#704]
I was trying to run tests for the nodejs buildpack (to ensure the behavior around alternative package manager selection is tested, since it appears to have changed in the past two days) but am encountering an error:

```shell
# install rust
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh

# clone the buildpack repo
git clone https://github.com/heroku/buildpacks-nodejs.git heroku/buildpacks-nodejs

# setup rust for the buildpack
cd heroku/buildpacks-nodejs
rustup update
rustup target add x86_64-unknown-linux-musl

# change to the buildpack in question
cd buildpacks/nodejs-npm-install

# attempt to run tests
INTEGRATION_TEST_CNB_BUILDER=heroku/builder:22 cargo test --locked -- --ignored --test-threads 16
```

<details>
  <summary>Output</summary>

```
warning: some crates are on edition 2021 which defaults to `resolver = "2"`, but virtual workspaces default to `resolver = "1"`
note: to keep the current resolver, specify `workspace.resolver = "1"` in the workspace root's manifest
note: to use the edition 2021 resolver, specify `workspace.resolver = "2"` in the workspace root's manifest
    Finished test [unoptimized + debuginfo] target(s) in 0.36s
     Running unittests src/main.rs (/Users/josediazgonzalez/go/src/github.com/heroku/buildpacks-nodejs/target/debug/deps/heroku_npm_install_buildpack-887ff546bb0ac9e4)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running tests/integration_test.rs (/Users/josediazgonzalez/go/src/github.com/heroku/buildpacks-nodejs/target/debug/deps/integration_test-ecd4a784e3c3adea)

running 6 tests
test test_npm_install_with_lockfile ... FAILED
test test_npm_install_caching ... FAILED
test test_npm_install_new_package ... FAILED
test test_npm_start_script_creates_a_web_process_launcher ... FAILED
test test_npm_build_scripts ... FAILED
test test_npm_build_scripts_prefers_heroku_build_over_build ... FAILED

failures:

---- test_npm_install_with_lockfile stdout ----
thread 'test_npm_install_with_lockfile' panicked at /Users/josediazgonzalez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libcnb-test-0.15.0/src/test_runner.rs:121:42:
Test references buildpack `heroku/nodejs`, but this directory wasn't packaged as a buildpack. This is an internal libcnb-test error, please report any occurrences

---- test_npm_install_caching stdout ----
thread 'test_npm_install_caching' panicked at /Users/josediazgonzalez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libcnb-test-0.15.0/src/test_runner.rs:121:42:
Test references buildpack `heroku/nodejs`, but this directory wasn't packaged as a buildpack. This is an internal libcnb-test error, please report any occurrences

---- test_npm_install_new_package stdout ----
thread 'test_npm_install_new_package' panicked at /Users/josediazgonzalez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libcnb-test-0.15.0/src/test_runner.rs:121:42:
Test references buildpack `heroku/nodejs`, but this directory wasn't packaged as a buildpack. This is an internal libcnb-test error, please report any occurrences
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- test_npm_start_script_creates_a_web_process_launcher stdout ----
thread 'test_npm_start_script_creates_a_web_process_launcher' panicked at /Users/josediazgonzalez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libcnb-test-0.15.0/src/test_runner.rs:121:42:
Test references buildpack `heroku/nodejs`, but this directory wasn't packaged as a buildpack. This is an internal libcnb-test error, please report any occurrences

---- test_npm_build_scripts stdout ----
thread 'test_npm_build_scripts' panicked at /Users/josediazgonzalez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libcnb-test-0.15.0/src/test_runner.rs:121:42:
Test references buildpack `heroku/nodejs`, but this directory wasn't packaged as a buildpack. This is an internal libcnb-test error, please report any occurrences

---- test_npm_build_scripts_prefers_heroku_build_over_build stdout ----
thread 'test_npm_build_scripts_prefers_heroku_build_over_build' panicked at /Users/josediazgonzalez/.cargo/registry/src/index.crates.io-6f17d22bba15001f/libcnb-test-0.15.0/src/test_runner.rs:121:42:
Test references buildpack `heroku/nodejs`, but this directory wasn't packaged as a buildpack. This is an internal libcnb-test error, please report any occurrences


failures:
    test_npm_build_scripts
    test_npm_build_scripts_prefers_heroku_build_over_build
    test_npm_install_caching
    test_npm_install_new_package
    test_npm_install_with_lockfile
    test_npm_start_script_creates_a_web_process_launcher

test result: FAILED. 0 passed; 6 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.01s

error: test failed, to rerun pass `--test integration_test`
```
</details>

Of note, I'm on MacOS Venture 13.6 on a Macbook Air M2, so maybe its an architecture thing?

**Comment by edmorley** [comment]
@jose-fully-ported Thank you for filing an issue.

When I run the tests locally I don't get that error message.

I notice in the STR, there's no mention of brew installing the cross-compilation requirements. If they are missing, then the framework should tell you to install them - or at least it used to. Perhaps this is an error message UX regression after the refactoring in #666 or one of the other similar PRs?

If you run `cargo install libcnb-cargo` (to install the libcnb cargo plugin) and then run `cargo libcnb package` from the ` buildpacks/nodejs-npm-install` directory, do you get the instructions about installing the needed requirements?

If not, then for now could you follow these steps and see if that allows the tests to succeed?
https://github.com/heroku/libcnb.rs/blob/cdd2eb4b4df8706ddee968bba05237ea90a1ffed/libcnb-package/src/cross_compile.rs#L21-L28

**Comment by edmorley** [comment]
Thank you.

Tomorrow I'll look into why `libcnb-test` isn't surfacing that more helpful error message - since it should have shown it too.

**Comment by edmorley** [comment]
Ok so this is a regression from #666 in libcnb-test 0.15.0:
https://github.com/heroku/libcnb.rs/commit/b59a9ce1e55190dbeb45a509519575affe0dbb89#diff-6889e352ea9b53638ed05fa3483ecc6259b1d24abff88b0180be53cafc25d000L108

The previous implementation had to unwrap a temp dir path at one point, and used the ~"but crate wasn't packaged as a buildpack" message for that.

In #666 the code was refactored and the same error message used when unwrapping a completely different return value (the result from packaging). 

Before when packaging failed a "Could not package current crate as buildpack" error was returned instead:
https://github.com/heroku/libcnb.rs/commit/b59a9ce1e55190dbeb45a509519575affe0dbb89#diff-6889e352ea9b53638ed05fa3483ecc6259b1d24abff88b0180be53cafc25d000L97

**Comment by edmorley** [comment]
Ah so there are two parts to the regression:
1. The error message shown is misleading (the text refers to an unrelated issue) for both packaging the current create, and packaging other crates.
2. When packaging other crates specifically, the error message is also now missing the debug representation of the underlying error, since that codepath uses `panic!` rather than `.expect()` - and when using `panic!` one has to manually include the underlying error in the message to fully replace the same behaviour as `.expect()` (because expect is equivalent to `panic!("{msg}: {error:?}")` not just `panic!("{msg}")`).

**Comment by edmorley** [comment]
In fact, it seems the regression was actually caught be the tests, but rather than the issue being investigated/fixed, the tests were rewritten to use `catch_unwind`, which will catch the lower level error rather than the expect/panic usage:
https://github.com/heroku/libcnb.rs/commit/b59a9ce1e55190dbeb45a509519575affe0dbb89#diff-6a86c81613708c6f5b78432f6f55d3a8de0a6c98ca1babdcb4ae8e683401f8f3L135

**Comment by edmorley** [comment]
In fact, it seems the regression was actually caught be the tests, which is why they ended up being changed in:  
https://github.com/heroku/libcnb.rs/commit/b59a9ce1e55190dbeb45a509519575affe0dbb89#diff-6a86c81613708c6f5b78432f6f55d3a8de0a6c98ca1babdcb4ae8e683401f8f3L135

The problem is that `assert!`s and Error return types are being mixed and matched - and the test tested a case which is now handled by an assert lower down the call stack than the now-broken error message.

IMO we should only be using asserts/panics/expects at the runner top level, and not in lower down helper functions.
